### ISSUE TITLE
Testing - Integration testing API

### ISSUE THREAD

**Issue by jonathanpmelian** [jonathanpmelian/MingL#32]
Validate event creation API communication

**Comment by MadhurSaluja** [comment]
@jonathanpmelian can I work on this?

**Comment by jonathanpmelian** [comment]
Hello @MadhurSaluja , thank you for your interest in contributing. 

This task still needs the development of other frontend functionalities. But, I have created this issue: https://github.com/jonathanpmelian/MingL/issues/41, which can be a good entry point to contribute and is also related to testing.

If you are interested, I will be glad if you can contribute.
